spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clubmanagement?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Rudtjr1216!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true